package gui;

import gui.controller.SettingsController;
import util.Translator;

public class SettingsPanel extends javax.swing.JPanel
{

    private SettingsController settingsController;

    public SettingsPanel()
    {

        initComponents();
        translate();

    }

    public void translate()
    {
        Translator trans = new Translator();
        jLabel2.setText(trans.translate("Language"));
        jButton1.setText(trans.translate("Back"));
        jButton3.setText(trans.translate("SetLanguage"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cbxLanguage = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("Language:");
        jLabel2.setMaximumSize(new java.awt.Dimension(120, 23));
        jLabel2.setMinimumSize(new java.awt.Dimension(120, 23));
        jLabel2.setPreferredSize(new java.awt.Dimension(120, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(jLabel2, gridBagConstraints);

        cbxLanguage.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "English", "Nederlands" }));
        cbxLanguage.setMaximumSize(new java.awt.Dimension(100, 23));
        cbxLanguage.setMinimumSize(new java.awt.Dimension(100, 23));
        cbxLanguage.setPreferredSize(new java.awt.Dimension(100, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 17;
        add(cbxLanguage, gridBagConstraints);

        jButton1.setText("Back");
        jButton1.setMaximumSize(new java.awt.Dimension(120, 23));
        jButton1.setMinimumSize(new java.awt.Dimension(120, 23));
        jButton1.setPreferredSize(new java.awt.Dimension(120, 23));
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        add(jButton1, gridBagConstraints);

        jButton3.setText("Set Language");
        jButton3.setMaximumSize(new java.awt.Dimension(120, 23));
        jButton3.setMinimumSize(new java.awt.Dimension(120, 23));
        jButton3.setPreferredSize(new java.awt.Dimension(120, 23));
        jButton3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        add(jButton3, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        settingsController.back();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3ActionPerformed
    {//GEN-HEADEREND:event_jButton3ActionPerformed
        int language = cbxLanguage.getSelectedIndex() + 1;
        settingsController.setLanguage(language);
        translate();
    }//GEN-LAST:event_jButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbxLanguage;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
    public void setSettingsController(SettingsController sc)
    {
        this.settingsController = sc;
    }
}
