/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui.controls;

import dto.PersonDTO;
import java.awt.Color;
import javax.swing.BorderFactory;

/**
 *
 * @author Sklipnoty
 */
public class PersonPanel extends javax.swing.JPanel {
    private PersonDTO person;

    /**
     * Creates new form PersonPanel
     */
    public PersonPanel(PersonDTO person) 
    {
        this.person = person;
        initComponents();
        firstNameLabel.setText(person.getFirstName());
        lastNameLabel.setText(person.getSurName());
        this.setBorder(BorderFactory.createLineBorder(Color.black));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("Lastname:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        add(jLabel2, gridBagConstraints);

        jLabel1.setText("Firstname:");
        add(jLabel1, new java.awt.GridBagConstraints());

        firstNameLabel.setText("jLabel3");
        add(firstNameLabel, new java.awt.GridBagConstraints());

        lastNameLabel.setText("jLabel4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        add(lastNameLabel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lastNameLabel;
    // End of variables declaration//GEN-END:variables
}
