/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui.controls;

import gui.controls.listeners.IViewFriendlistListener;
import gui.controls.listeners.ILogoutListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;

/**
 *
 * @author Lowie
 */
public class AccountOptionsControl extends javax.swing.JPanel {

    protected List<ILogoutListener> logoutListeners;
    protected List<IViewFriendlistListener> friendlistListeners;

    public String getUsername() {
        return lblUsername.getText();
    }

    public void setUsername(String username) {
        this.lblUsername.setText(username);
    }
    
    /**
     * Creates new form AccountOptions
     */
    public AccountOptionsControl() {
        initComponents();
    }
    
    public void addLogoutEventListener(ILogoutListener listener)
    {
        if (logoutListeners == null)
            logoutListeners = new ArrayList<ILogoutListener>();
             
        logoutListeners.add(listener);
    }
    public void addFriendlistEventListener(IViewFriendlistListener listener)
    {
        if (friendlistListeners == null)
            friendlistListeners = new ArrayList<IViewFriendlistListener>();
             
        friendlistListeners.add(listener);
    }
     
    protected void fireLogoutEvent()
    {
        if (logoutListeners != null)
        {
            for (ILogoutListener listener : logoutListeners) {
                listener.Logout();
            }
        }
    }
    protected void fireFriendlistEvent()
    {
        if (friendlistListeners != null)
        {
            for (IViewFriendlistListener listener : friendlistListeners) {
                listener.ViewFriendlist();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnShowFriendlist = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));

        setMinimumSize(new java.awt.Dimension(125, 0));
        setLayout(new java.awt.GridBagLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Account"));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Welcome, ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel2.add(jLabel1, gridBagConstraints);

        lblUsername.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblUsername.setText("lrhuyghe");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel2.add(lblUsername, gridBagConstraints);

        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setLayout(new java.awt.GridLayout(0, 1, 0, 5));

        btnShowFriendlist.setText("Show friendlist");
        btnShowFriendlist.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnShowFriendlist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnShowFriendlistMouseReleased(evt);
            }
        });
        jPanel1.add(btnShowFriendlist);

        btnLogOut.setText("Log out");
        btnLogOut.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnLogOutMouseReleased(evt);
            }
        });
        jPanel1.add(btnLogOut);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel2.add(jPanel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel2.add(filler1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        add(jPanel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        add(filler2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowFriendlistMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowFriendlistMouseReleased
        fireLogoutEvent();
    }//GEN-LAST:event_btnShowFriendlistMouseReleased

    private void btnLogOutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOutMouseReleased
        fireLogoutEvent();
    }//GEN-LAST:event_btnLogOutMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnShowFriendlist;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblUsername;
    // End of variables declaration//GEN-END:variables
}