/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.controls;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.border.Border;

/**
 *
 * @author Lowie
 */
public class CustomFormField extends javax.swing.JPanel {

    private Border defaultBorder;
    private Border errorBorder;
    
    public String getTitle() {
        return lblTitle.getText();
    }
    
    public void setTitle(String title) {
        lblTitle.setText(title);
    }
    
    public String getText() {
        return txtField.getText();
    }
    
    public void setText(String text) {
        txtField.setText(text);
    }
    
    public String getError() {
        return lblError.getText();
    }
    
    public void setError(String error) {
        lblError.setText(error);
        
        if (error.isEmpty())
        {
            txtField.setBorder(defaultBorder);
        } else {
            txtField.setBorder(errorBorder);
        }
    }
    
    
    public CustomFormField() {
        initComponents();
        init();
    }

    private void init() {
        defaultBorder = txtField.getBorder();
        errorBorder = BorderFactory.createLineBorder(Color.red);
        
        setError("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtField = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();

        txtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTitle.setText("Title");
        lblTitle.setName(""); // NOI18N

        lblError.setForeground(new java.awt.Color(255, 0, 0));
        lblError.setText("error");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtField)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblError, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblError))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtField;
    // End of variables declaration//GEN-END:variables
}
