/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.controls;

import java.awt.Color;
import javax.swing.border.Border;

/**
 *
 * @author Lowie
 */
public class CustomTextField extends javax.swing.JPanel {

    private String defaultText;
    
    public String getDefaultText() {
        return defaultText;
    }

    public void setDefaultText(String defaultText) {
        this.defaultText = defaultText;
        
        textFieldCheck();
    }

    public String getText() {
        return txtField.getText();
    }

    public void setText(String text) {
        txtField.setText(text);
        
        textFieldCheck();
    }

    public Border getTextBorder() {
        return txtField.getBorder();
    }

    public void setTextBorder(Border border) {
        txtField.setBorder(border);
    }

    public CustomTextField() {
        initComponents();
    }

    private void textFieldCheck() {
        String text = getText();
        if (!text.isEmpty() && !text.equals(defaultText))
        {
//            if (text.isEmpty())
//                setText(defaultText);
            txtField.setForeground(Color.black);
        } else {
            txtField.setForeground(Color.gray);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtField = new javax.swing.JTextField();

        txtField.setText("CustomTextField");
        txtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFieldKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtField, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtField)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldKeyReleased
        textFieldCheck();
    }//GEN-LAST:event_txtFieldKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField txtField;
    // End of variables declaration//GEN-END:variables
}
