/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui.controls;

import gui.controls.listeners.IOpenFamilyTreeListener;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Lowie
 */
public class FamiliyTreeListItem extends javax.swing.JPanel {

    private List<IOpenFamilyTreeListener> openFamilyTreeListeners;
    private int privacy = 0;

    public int getPrivacy() {
        return privacy;
    }
    public void setPrivacy(int privacy) {
        this.privacy = privacy;
        
        switch (privacy) {
            case 2:
                lblPrivacy.setText("Public");
                break;
            case 1:
                lblPrivacy.setText("Shared");
                break;
            case 0:
                lblPrivacy.setText("Private");
                break;
            default:
                lblPrivacy.setText("Unknown (<0 || >2)");
                break;
        }
    }
    
    /**
     * Creates new form FamiliyTreeListItem
     */
    public FamiliyTreeListItem() {
        initComponents();
    }
    
    public void addFriendlistEventListener(IOpenFamilyTreeListener listener)
    {
        if (openFamilyTreeListeners == null)
            openFamilyTreeListeners = new ArrayList<IOpenFamilyTreeListener>();
             
        openFamilyTreeListeners.add(listener);
    }
     
    protected void fireLogoutEvent()
    {
        if (openFamilyTreeListeners != null)
        {
            for (IOpenFamilyTreeListener listener : openFamilyTreeListeners) {
                listener.OpenFamilyTree();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnOpen = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        lblPrivacy = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setMinimumSize(new java.awt.Dimension(250, 33));
        setPreferredSize(new java.awt.Dimension(300, 33));
        setLayout(new java.awt.GridBagLayout());

        btnOpen.setText("Open");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 11, 5, 11);
        add(btnOpen, gridBagConstraints);

        lblName.setText("Family Tree Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 11, 0, 0);
        add(lblName, gridBagConstraints);

        lblPrivacy.setText("Private");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(lblPrivacy, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOpen;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPrivacy;
    // End of variables declaration//GEN-END:variables
}
