/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.controls;

import dto.ThemeDTO;
import dto.TreeDTO;
import java.awt.Color;
import java.awt.Font;
import javax.swing.ImageIcon;
import javax.swing.border.MatteBorder;
import service.ClientServiceController;
import util.Translator;

public class FamilyTreeListItem extends javax.swing.JPanel
{

    private FamilyTreeList familyTreeList;
    private int privacy = 0;
    private TreeDTO tree;

    public String getFamilyTreeName()
    {
        return lblName.getText();
    }

    public FamilyTreeList getFamilyTreeList()
    {
        return familyTreeList;
    }

    private void setFamilyTreeList(FamilyTreeList familyTreeList)
    {
        this.familyTreeList = familyTreeList;
    }

    private void setFamilyTreeName(String name)
    {
        lblName.setText(name);
    }

    public TreeDTO getTree()
    {
        return tree;
    }

    private void setTree(TreeDTO tree)
    {
        this.tree = tree;
    }

    public int getPrivacy()
    {
        return privacy;
    }

    private void setPrivacy(int privacy)
    {
        Translator trans = new Translator();
        this.privacy = privacy;
        String icon = null;

        switch (privacy)
        {
            case 2:
                icon = "PUBLIC";
                break;
            case 1:
                icon = "FRIENDS";
                break;
            case 0:
                icon = "PRIVATE";
                break;
        }
        lblPrivacy.setIcon(new ImageIcon(this.getClass().getClassLoader().getResource("images/" + icon + ".png")));
    }

    /**
     * Creates new form FamiliyTreeListItem
     *
     * @param name
     * @param privacy
     */
    public FamilyTreeListItem()
    {
        initComponents();
        initGui();
    }

    private void initGui()
    {
        ThemeDTO theme = ClientServiceController.getInstance().getUser().getUserSettings().getTheme();
        Color bgColor = ThemeDTO.toColor(theme.getBgColor());
        Color maleColor = ThemeDTO.toColor(theme.getMaleColor());

        this.lblName.setFont(ClientServiceController.getInstance().getUser().getUserSettings().getTheme().getDefaultFont());
        pnlBg.setBackground(bgColor);

        this.setBorder(new MatteBorder(0, 5, 0, 0, maleColor));
    }

    public FamilyTreeListItem(String name, int privacy, FamilyTreeList famTreeList, TreeDTO tree)
    {
        this();
        setFamilyTreeName(name);
        setPrivacy(privacy);
        setFamilyTreeList(famTreeList);
        setTree(tree);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlBg = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblPrivacy = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(350, 75));
        setMinimumSize(new java.awt.Dimension(150, 75));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(350, 75));
        setRequestFocusEnabled(false);
        setLayout(new java.awt.GridBagLayout());

        pnlBg.setBackground(new java.awt.Color(255, 255, 255));
        pnlBg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlBg.setMaximumSize(new java.awt.Dimension(350, 75));
        pnlBg.setMinimumSize(new java.awt.Dimension(150, 75));
        pnlBg.setPreferredSize(new java.awt.Dimension(350, 75));
        pnlBg.setRequestFocusEnabled(false);
        pnlBg.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                pnlBgformMouseClicked(evt);
            }
        });
        pnlBg.setLayout(new java.awt.GridBagLayout());

        lblName.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblName.setText("Family Tree Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 11, 0, 0);
        pnlBg.add(lblName, gridBagConstraints);

        lblPrivacy.setText(" ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 10);
        pnlBg.add(lblPrivacy, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(pnlBg, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        add(filler1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void pnlBgformMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_pnlBgformMouseClicked
    {//GEN-HEADEREND:event_pnlBgformMouseClicked
        this.familyTreeList.openFamilyTree(tree);
    }//GEN-LAST:event_pnlBgformMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPrivacy;
    private javax.swing.JPanel pnlBg;
    // End of variables declaration//GEN-END:variables

}
