#!perl/bin/perl
use strict;
use warnings;
use LWP::Simple;
use HTML::TreeBuilder;
use DBI;
use Modern::Perl;
use WWW::Mechanize;
use HTML::TableExtract;



my $db ="team12_staging";
my $user = "team12";
my $pass = "RKAxujnJ";
my $host="db.vop.tiwi.be:443";
my $dbh = DBI->connect("DBI:mysql:$db:$host", $user, $pass);



my $queryUser = "insert into User (username,password) 
      values (?,?)";
my $queryTree = "insert into Tree (ownerID,privacy,name) 
      values (?,?,?)";
my $queryPersonTree = "insert into PersonTree (treeID,personID) 
      values (?,?)";
my $queryPerson = "insert into Person (birthplace,firstname,lastname,gender) 
      values (?,?,?,?)";     
my $queryParentrelation = "insert into ParentRelation (treeID,parent,child) 
      values (?,?,?)";     


my $sqlQueryUser  = $dbh->prepare($queryUser)
or die "";


my $sqlQueryTree  = $dbh->prepare($queryTree)
or die "";


my $sqlQueryPersonTree  = $dbh->prepare($queryPersonTree)
or die "";

my $sqlQueryPerson  = $dbh->prepare($queryPerson)
or die "";

my $sqlQueryParentrelation  = $dbh->prepare($queryParentrelation)
or die "";

my $firstURL= "http://www.naamkunde.net/?page_id=293&vt_list_female=true";
my $secondURL = "http://www.naamkunde.net/?page_id=293&vt_list_male=true";
my $surURL = "http://home.scarlet.be/~rg588291/surname.htm";



my $site = get($surURL);

my $femaleTree = HTML::TreeBuilder->new_from_url($firstURL);
my $maleTree = HTML::TreeBuilder->new_from_url($secondURL);
my $surTree = HTML::TreeBuilder->new_from_url($surURL);
my @femalenames;
my @malenames;
my @surnames;
my @User;


foreach my $sur ($surTree->look_down(_tag => 'a',sub { $_[0]->as_text =~/^[a-zA-Z]/})){
 
  push @surnames,ucfirst(lc($sur->as_text));
};

foreach my $female ($femaleTree->look_down(_tag => 'td',sub { $_[0]->as_text =~/^[a-zA-Z]/})){
  push @femalenames,substr($female->as_text, 0, -3)
};
foreach my $male ($maleTree->look_down(_tag => 'td',sub { $_[0]->as_text =~/^[a-zA-Z]/})){
  push @malenames,substr($male->as_text, 0, -3)
};

  
    for (my $i = @femalenames; --$i; ) {
        my $j = int rand ($i+1);
        next if $i == $j;
        @femalenames[$i,$j] = @femalenames[$j,$i];
    }

 
    for (my $y = @malenames; --$y; ) {
        my $j = int rand ($y+1);
        next if $y == $j;
        @malenames[$y,$j] = @malenames[$j,$y];
    }

   
    for (my $z = @surnames; --$z; ) {
        my $j = int rand ($z+1);
        next if $z == $j;
        @surnames[$z,$j] = @surnames[$j,$z];
    }

my $teller = 0;
$sqlQueryUser->execute('Logitech','Logitech');
my $userID = $dbh->last_insert_id(undef, undef, undef, undef);
 my $range = 2;

 

for(my $i = 0; $i  < 1; $i++){
  

$sqlQueryTree->execute($userID,int(rand($range)),$surnames[$i]);
my $tree =$dbh->last_insert_id(undef, undef, undef, undef);

my @Lijst;
my $aantal = 2;

      for(my $y = 0; $y  < 10 ; $y++){
          $sqlQueryPerson->execute(4,$femalenames[$teller],$surnames[$i],1);
          my $pID = $dbh->last_insert_id(undef, undef, undef, undef);

           push @Lijst,$pID;
          $sqlQueryPersonTree->execute($tree,$pID);
          $sqlQueryPerson->execute(4,$malenames[$teller],$surnames[$i],0);
          push @Lijst,$dbh->last_insert_id(undef, undef, undef, undef);
          $sqlQueryPersonTree->execute($tree,$dbh->last_insert_id(undef, undef, undef, undef));
          $teller++;}

          $sqlQueryPerson->execute(4,$femalenames[$teller],$surnames[$i],1);
           push @Lijst,$dbh->last_insert_id(undef, undef, undef, undef);




 my $start = 8;

  for(my $parent = 2 ; $parent <= 6;$parent+=2){
      $sqlQueryParentrelation->execute($tree,$Lijst[0],$Lijst[$parent]);
      $sqlQueryParentrelation->execute($tree,$Lijst[1],$Lijst[$parent]);
   my $max = $start + 4;
        for(my $child = $start; $child < $max ;$child+=2){
            $sqlQueryParentrelation->execute($tree,$Lijst[$parent],$Lijst[$child]);
            $sqlQueryParentrelation->execute($tree,$Lijst[$parent+1],$Lijst[$child]);
          }
            $start+=4;
   }


   
   


}
